// Generated by Selenium IDE

package es.uca.iw.FuntionalTesting;


import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistroUsuarioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registroUsuario() {
    driver.get("http://localhost:8080/web/");
    driver.manage().window().setSize(new Dimension(1306, 824));
    driver.findElement(By.cssSelector(".mx-auto:nth-child(3)")).click();
    driver.findElement(By.id("input-vaadin-text-field-24")).click();
    driver.findElement(By.id("input-vaadin-text-field-25")).click();
    driver.findElement(By.id("input-vaadin-text-field-26")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.cssSelector("vaadin-password-field:nth-child(4)")).click();
    driver.findElement(By.id("input-vaadin-text-field-28")).click();
    driver.findElement(By.id("input-vaadin-password-field-29")).click();
    driver.findElement(By.cssSelector("vaadin-password-field:nth-child(6) > vaadin-password-field-button")).click();
    driver.findElement(By.cssSelector("vaadin-password-field:nth-child(4) > vaadin-password-field-button")).click();
    driver.findElement(By.id("input-vaadin-email-field-30")).click();
    driver.findElement(By.id("input-vaadin-text-field-31")).click();
    driver.findElement(By.cssSelector("vaadin-button")).click();
  }
}
