// Generated by Selenium IDE

package es.uca.iw.FunctionalTesting;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;


public class LogInTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logIn() {
    driver.get("http://localhost:8080/web/");
    driver.manage().window().setSize(new Dimension(1306, 824));
    driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
    driver.findElement(By.cssSelector("vaadin-vertical-layout > vaadin-vertical-layout > vaadin-vertical-layout")).click();
    driver.findElement(By.cssSelector("#vaadinLoginFormWrapper > vaadin-button:nth-child(2)")).click();
  }
}
